# ==========================================================
# 🚀 Build and Deploy ASP.NET Core API to Azure Web App (DEV)
# Ambiente: Desenvolvimento (Branch develop)
# Serviço destino: api-versopay-dev (Azure App Service)
# ==========================================================

name: Build and deploy DEV API to Azure Web App - api-versopay-dev

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    name: Build .NET API
    runs-on: windows-latest
    permissions:
      contents: read # Necessário para actions/checkout

    steps:
      # -------------------------------
      # 1. Clonar o repositório
      # -------------------------------
      - name: Checkout source code
        uses: actions/checkout@v4

      # -------------------------------
      # 2. Configurar .NET 8 SDK
      # -------------------------------
      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # -------------------------------
      # 3. Restaurar dependências
      # -------------------------------
      - name: Restore dependencies
        run: dotnet restore ./VersopayBackend.csproj

      # -------------------------------
      # 4. Buildar o projeto
      # -------------------------------
      - name: Build with dotnet
        run: dotnet build ./VersopayBackend.csproj --configuration Release --no-restore

      # -------------------------------
      # 5. Publicar o build
      # -------------------------------
      - name: dotnet publish
        run: dotnet publish ./VersopayBackend.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp" --no-build

      # -------------------------------
      # 6. Enviar artefato para o deploy
      # -------------------------------
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    name: Deploy to Azure Web App
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write # Necessário para autenticação OIDC
      contents: read

    steps:
      # -------------------------------
      # 1. Baixar artefato do build
      # -------------------------------
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      # -------------------------------
      # 2. Login no Azure
      # -------------------------------
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BCE3C5D083174005815CB3460D35237A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_708C9628B9CA4F3EA31EB42A166023C6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_65310B31D35C4E51994B137389511DB1 }}

      # -------------------------------
      # 3. Deploy no App Service
      # -------------------------------
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'api-versopay-dev'
          slot-name: 'Production'
          package: .

